fix(Messanger.tsx) : src/pages/Messanger.tsx(45,18): error TS2740: Type '{ messageArray: MessageTypesPopulated[]; }' is missing the following properties from type '{ messageArray: MessageTypesPopulated[] | []; isMessageSelectionActive: boolean; selectedMessages: MessageTypesPopulated[]; setIsDialogOpen: Dispatch<...>; isDeleteForMeClicked: boolean; setIsDeleteForMeClicked: Dispatch<...>; isDeleteForAllClicked: boolean; setIsDeleteForAllClicked: Dispatch<...>; }': isMessageSelectionActive, selectedMessages, setIsDialogOpen, isDeleteForMeClicked, and 3 more.